tasks:
  - name: permissao
    init: echo 'mudando permissão'
    command: chmod -R 777 .
  - name: jupyter
    init: echo 'iniciando'
    command: docker-compose up --build -d
      
  
ports:
  - port: 3000-8999
    onOpen: open-browser
    visibility: public