version:    "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - /workspace/workshop_ML_RN/notebook:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: datascience-notebook-container